### ISSUE TITLE
Вопрос 1

### ISSUE THREAD

**Issue by nzhukov** [python-advance/sem6-t2-AnotherStudent#1]
https://github.com/python-advance/sem6-t2-AnotherStudent/blob/aef3565378ecb4e1512c7f7799bb305548e69e8e/iterator.py#L36

Написать несколько тестов.

**Comment by AnotherStudent** [comment]
Уже: https://github.com/python-advance/sem6-t2-AnotherStudent/blob/master/iterator.py#L37
